name: Higgs Shop Sample App Pull Request

on:
    workflow_call:
      inputs:
        app_relative_path:
          description: 'repo path for sample app'
          required: true
          type: string
    
defaults:
    run:
        # Should be: working-directory: ${{ inputs.app_relative_path }}
        working-directory: core-sdk-samples/higgs-shop-sample-app

jobs:
    build-and-test:
        name: Build, Lint, and Test
        runs-on: ${{ matrix.os }}
        continue-on-error: true  # Prevents parallel job from being cancelled if all fail
        strategy:
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]
                node-version: [16.x, 17.x, 18.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: NPM install ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Run NPM CI
              run: npm ci

            - name: Lint with ESLint
              run: npm run lint

            - name: Lint with Prettier
              run: npm run prettier

            - name: Build Files
              run: npm run build

            - name: Run tests
              run: npm run test

            - name: Archive npm failure logs
              uses: actions/upload-artifact@v3
              if: failure()
              with:
                name: npm-logs
                path: ~/.npm/_logs
